# Generated by Django 3.2.10 on 2022-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organizations', '0003_historicalorganizationcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sites',
            field=models.ManyToManyField(related_name='organizations', to='sites.Site'),
        ),
    ]
