# Generated by Django 3.2.10 on 2022-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20220419_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizationmapping',
            name='is_amc_admin',
            field=models.BooleanField(default=False),
        ),
    ]
