# Generated by Django 4.2.20 on 2026-07-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


ORGANIZATION_TYPE_CHOICES = [
    ('k12_school', 'K-12 School'),
    ('school_district', 'School District or Education Agency'),
    ('career_technical_center', 'Career/Technical or Trade School'),
    ('homeschool', 'Homeschool'),
    ('college_university', 'College or University'),
    ('training_provider', 'Training or Adult Education Provider'),
    ('workforce_agency', 'Workforce Development Organization'),
    ('education_nonprofit', 'Education or Community Organization'),
    ('education_technology', 'Education Technology Provider'),
    ('employer', 'Employer or Industry Organization'),
    ('government_agency', 'Government Agency'),
    ('internal_program', 'Internal Program'),
    ('other', 'Other'),
    ('unknown', 'Unknown'),
]

EDUCATION_LEVEL_CHOICES = [
    ('early_childhood', 'Early Childhood'),
    ('elementary_school', 'Elementary School'),
    ('elementary_middle', 'Elementary and Middle School'),
    ('middle_school', 'Middle School'),
    ('high_school', 'High School'),
    ('secondary', 'Secondary School'),
    ('k12', 'K-12'),
    ('secondary_adult', 'Secondary and Adult Workforce'),
    ('postsecondary_nondegree', 'Postsecondary Non-Degree'),
    ('postsecondary', 'Postsecondary'),
    ('adult_workforce', 'Adult Workforce'),
    ('continuing_education', 'Continuing Education'),
    ('all_levels', 'Multiple or All Education Levels'),
    ('not_applicable', 'Not Applicable'),
    ('unknown', 'Unknown'),
]

GOVERNANCE_TYPE_CHOICES = [
    ('public', 'Public'),
    ('public_charter', 'Public Charter'),
    ('federal_government', 'Federal Government'),
    ('state_government', 'State Government'),
    ('local_government', 'Local Government'),
    ('tribal_government', 'Tribal Government'),
    ('government', 'Government Agency'),
    ('private_nonprofit', 'Private Nonprofit'),
    ('private_for_profit', 'Private For-Profit'),
    ('private', 'Private'),
    ('nonprofit', 'Nonprofit'),
    ('cooperative', 'Cooperative'),
    ('labor_management', 'Labor-Management Partnership'),
    ('internal', 'Internal'),
    ('unknown', 'Unknown'),
]


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_historicalorganization_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='education_level',
            field=models.CharField(
                choices=EDUCATION_LEVEL_CHOICES,
                db_index=True,
                default='unknown',
                max_length=32,
                verbose_name='Education Level',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='governance_type',
            field=models.CharField(
                choices=GOVERNANCE_TYPE_CHOICES,
                db_index=True,
                default='unknown',
                max_length=32,
                verbose_name='Governance Type',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='organization_type',
            field=models.CharField(
                choices=ORGANIZATION_TYPE_CHOICES,
                db_index=True,
                default='unknown',
                max_length=32,
                verbose_name='Organization Type',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='education_level',
            field=models.CharField(
                choices=EDUCATION_LEVEL_CHOICES,
                db_index=True,
                default='unknown',
                max_length=32,
                verbose_name='Education Level',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='governance_type',
            field=models.CharField(
                choices=GOVERNANCE_TYPE_CHOICES,
                db_index=True,
                default='unknown',
                max_length=32,
                verbose_name='Governance Type',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(
                choices=ORGANIZATION_TYPE_CHOICES,
                db_index=True,
                default='unknown',
                max_length=32,
                verbose_name='Organization Type',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='parent_organization',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Optional district or parent organization. Create it as an organization before assigning it.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='organizations.organization',
                verbose_name='District / Parent Organization',
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional district or parent organization. Create it as an organization before assigning it.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_organizations',
                to='organizations.organization',
                verbose_name='District / Parent Organization',
            ),
        ),
    ]
