# Generated by Django 4.2.20 on 2026-07-22

from django.db import migrations, models


def copy_standalone_description_urls(apps, schema_editor):
    """Copy descriptions containing only one HTTP(S) URL into website_url."""
    for model_name in ('Organization', 'HistoricalOrganization'):
        model = apps.get_model('organizations', model_name)
        queryset = model.objects.exclude(description__isnull=True).exclude(description='')
        for organization in queryset.iterator():
            description = organization.description.strip()
            if description.startswith(('http://', 'https://')) and not any(
                character.isspace() for character in description
            ):
                organization.website_url = description
                organization.save(update_fields=['website_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_classifications_and_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Website URL'),
        ),
        migrations.RunPython(copy_standalone_description_urls, migrations.RunPython.noop),
    ]
