# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-11-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organizations', '0006_auto_20171207_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sites',
            field=models.ManyToManyField(related_name='organizations', to='sites.Site'),
        ),
    ]
