# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-11-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20211123_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizationmapping',
            name='is_amc_admin',
            field=models.BooleanField(default=False),
        ),
    ]
