# Generated by Django 3.2.13 on 2024-09-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20240724_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganizationinstitutioncourse',
            name='organization',
        ),
        migrations.AddField(
            model_name='historicalorganizationinstitutioncourse',
            name='institution',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organizationinstitution'),
        ),
        migrations.AddField(
            model_name='organizationinstitutioncourse',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationinstitution'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationinstitutioncourse',
            unique_together={('course_id', 'institution')},
        ),
        migrations.RemoveField(
            model_name='organizationinstitutioncourse',
            name='organization',
        ),
    ]
