# Generated by Django 3.2.13 on 2024-09-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20240910_0102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinstitutioncourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organizationinstitutioncourse',
            name='institution',
        ),
        migrations.DeleteModel(
            name='HistoricalOrganizationInstitutionCourse',
        ),
        migrations.DeleteModel(
            name='OrganizationInstitutionCourse',
        ),
    ]
