# Generated by Django 4.2.19 on 2025-06-17 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0012_auto_20240911_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organization', 'verbose_name_plural': 'historical organizations'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganizationcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Link Course Organization', 'verbose_name_plural': 'historical Link Courses Organization'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganizationinstitution',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organization institution', 'verbose_name_plural': 'historical organization institutions'},
        ),
        migrations.AlterModelOptions(
            name='organizationcourse',
            options={'verbose_name': 'Link Course Organization', 'verbose_name_plural': 'Link Courses Organization'},
        ),
        migrations.CreateModel(
            name='HistoricalOrganizationInstitutionCourse',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID')),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organizationinstitution')),
            ],
            options={
                'verbose_name': 'historical Link Course Institution',
                'verbose_name_plural': 'historical Link Courses Institution',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationInstitutionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID')),
                ('active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationinstitution')),
            ],
            options={
                'verbose_name': 'Link Course Institution',
                'verbose_name_plural': 'Link Courses Institution',
                'unique_together': {('course_id', 'institution')},
            },
        ),
    ]
