# Generated by Django 4.2.30 on 2026-07-22 11:43

from django.db import migrations, models


def copy_parent_organizations(apps, schema_editor):
    """Preserve each existing foreign-key parent in the new many-to-many table."""
    organization_model = apps.get_model("organizations", "Organization")
    through_model = organization_model.parent_organizations.through
    through_model.objects.bulk_create(
        through_model(
            from_organization_id=organization_id,
            to_organization_id=parent_id,
        )
        for organization_id, parent_id in organization_model.objects.exclude(
            parent_organization_id__isnull=True
        ).values_list("id", "parent_organization_id")
    )


def restore_single_parent_organization(apps, schema_editor):
    """Restore one deterministic parent when reversing to the foreign-key schema."""
    organization_model = apps.get_model("organizations", "Organization")
    through_model = organization_model.parent_organizations.through
    relationships = through_model.objects.order_by(
        "from_organization_id", "to_organization_id"
    ).values_list("from_organization_id", "to_organization_id")
    restored_children = set()
    for child_id, parent_id in relationships:
        if child_id not in restored_children:
            organization_model.objects.filter(pk=child_id).update(parent_organization_id=parent_id)
            restored_children.add(child_id)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_organization_and_parent_website_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="parent_organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional districts or parent organizations. Create them as organizations before assigning them.",
                related_name="child_organizations",
                to="organizations.organization",
                verbose_name="District / Parent Organizations",
            ),
        ),
        migrations.RunPython(copy_parent_organizations, restore_single_parent_organization),
        migrations.RemoveField(
            model_name="organization",
            name="parent_organization",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="parent_organization",
        ),
    ]
