# Generated by Django 4.2.30 on 2026-07-25

from django.db import migrations, models


OLD_ORGANIZATION_TYPE = "career_technical_center"
NEW_ORGANIZATION_TYPE = "career_technical_education"

ORGANIZATION_TYPE_CHOICES = [
    ("k12_school", "K-12 School"),
    ("school_district", "School District or Education Agency"),
    ("career_technical_education", "Career & Technical Education Center"),
    ("homeschool", "Homeschool"),
    ("college_university", "College or University"),
    ("training_provider", "Training or Adult Education Provider"),
    ("workforce_agency", "Workforce Development Organization"),
    ("education_nonprofit", "Education or Community Organization"),
    ("education_technology", "Education Technology Provider"),
    ("employer", "Employer or Industry Organization"),
    ("government_agency", "Government Agency"),
    ("internal_program", "Internal Program"),
    ("other", "Other"),
    ("unknown", "Unknown"),
]


def rename_career_technical_organization_type(apps, schema_editor):
    """Move current and historical organizations to the new stable type value."""
    organization = apps.get_model("organizations", "Organization")
    historical_organization = apps.get_model("organizations", "HistoricalOrganization")

    organization.objects.filter(
        organization_type=OLD_ORGANIZATION_TYPE,
    ).update(organization_type=NEW_ORGANIZATION_TYPE)
    historical_organization.objects.filter(
        organization_type=OLD_ORGANIZATION_TYPE,
    ).update(organization_type=NEW_ORGANIZATION_TYPE)


def restore_career_technical_organization_type(apps, schema_editor):
    """Restore the previous type value when reversing this migration."""
    organization = apps.get_model("organizations", "Organization")
    historical_organization = apps.get_model("organizations", "HistoricalOrganization")

    organization.objects.filter(
        organization_type=NEW_ORGANIZATION_TYPE,
    ).update(organization_type=OLD_ORGANIZATION_TYPE)
    historical_organization.objects.filter(
        organization_type=NEW_ORGANIZATION_TYPE,
    ).update(organization_type=OLD_ORGANIZATION_TYPE)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0019_remove_historicalorganization_parent_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(
            rename_career_technical_organization_type,
            restore_career_technical_organization_type,
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="organization_type",
            field=models.CharField(
                choices=ORGANIZATION_TYPE_CHOICES,
                db_index=True,
                max_length=32,
                verbose_name="Organization Type",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=ORGANIZATION_TYPE_CHOICES,
                db_index=True,
                max_length=32,
                verbose_name="Organization Type",
            ),
        ),
    ]
